name = "Kedrovsky"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.38.1"

[author]
  name = "Karl Kedrovsky"
  homepage = "http://www.kedrovsky.com"